version: '3.1'
services:
  letsencrypt-nginx-container:
    container_name: 'letsencrypt-nginx-container'
    volumes:
      - /home/ubuntu:/usr/share/nginx/html
    build:
      context: .
      dockerfile: ./Dockerfile.letsencrypt
    ports:
      - "80:80"