export default {
	SET_ID: 'RECORDING__SET_ID',
	SET_FILTER: 'RECORDING__SET_FILTER',
	GET_ALL: 'RECORDING__GET_ALL',
	GET_SETTINGS: 'RECORDING__GET_SETTINGS',
	UPDATE_SETTINGS: 'RECORDING__UPDATE_SETTINGS',
};
